[platformio]
src_dir = src
default_envs = nrf52840

[env:nrf52840]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
monitor_speed = 115200
build_flags =
    -DBOARD_VARIANT=\"nrf52840\"
lib_deps =
    adafruit/Adafruit nRF52@>=1.3.0
