[platformio]
src_dir = src
default_envs = nrf52840

[env:nrf52840]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840
framework = arduino
monitor_speed = 115200
build_flags =
    -DBOARD_VARIANT=\"nrf52840\"
lib_deps =
    adafruit/Adafruit SPIFlash@>=4.0.0
    adafruit/SdFat - Adafruit Fork@>=1.4.0
