[platformio]
src_dir = src
default_envs = xiao_nrf52840

[env:xiao_nrf52840]
platform = nordicnrf52
board = seeed_xiao_nrf52840
framework = arduino
monitor_speed = 115200
build_flags =
    -DBOARD_VARIANT=\"nrf52840\"
lib_deps =
    adafruit/Adafruit SPIFlash@>=4.0.0
    adafruit/SdFat - Adafruit Fork@>=1.4.0
