[platformio]
src_dir = IsChrisVaping
default_envs = esp32

[env]
platform = espressif32
board = esp32dev
framework = arduino, espidf
board_build.f_cpu = 80000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
monitor_speed = 115200
upload_speed = 115200
upload_port = COM10
lib_ldf_mode = deep+
lib_extra_dirs =
    ~/.platformio/packages/framework-arduinoespressif32/libraries
build_flags =
    -DCONFIG_AUTOSTART_ARDUINO=1
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ST7735 and ST7789 Library
    BLE

[env:esp32]
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
build_flags =
    ${env.build_flags}
    -DBOARD_VARIANT=\"esp32\"

[env:esp32_4mb]
board_upload.flash_size = 4MB
board_build.partitions = partitions_4mb.csv
build_flags =
    ${env.build_flags}
    -DBOARD_VARIANT=\"esp32_4mb\"
